name: "Test and Fix"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  prittier:
    name: "Fix"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run fix
      - uses: EndBug/add-and-commit@v7
        with:
          add: bin lib src test
